package scanner;

// package simplescanner;

/**
* An enum is used to restrict the value of the token type to those that are specified.
* 
*/
public enum TokenType {
 LEFTPAR, RIGHTPAR, LEFTBRACKET, RIGHTBRACKET, LEFTCURL, RIGHTCURL,
 PLUS, MINUS, EQUAL, LESSTHAN, LESSTHANEQ, GREATERTHAN, GREATERTHANEQ,
 MULTIPLY, DIVIDE, COLON, SEMI, COMMA, PERIOD, ASSIGN, NOTEQUAL,
 AND, OR, MOD, DIV, VAR, OF, NOT, IF, ELSE, THEN, DO, WHILE, BEGIN,
 END, PROGRAM, ARRAY, FUNCTION, REAL, INTEGER, PROCEDURE, OPEN, CLOSE,
 NUMBER, ID, ERROR, READ,WRITE,RETURN, ASTERISK, SLASH
}
